### ISSUE TITLE
时

### ISSUE THREAD

**Issue by xtzpioneer** [shaokui-gu/GMDatePicker#2]
时间选中完成后是前一天的时间，比如我选择时间为2022年8月8日，选中完成后变成了2022年8月7日。

**Comment by shaokui-gu** [comment]
> 时间选中完成后是前一天的时间，比如我选择时间为2022年8月8日，选中完成后变成了2022年8月7日。

我自己测试没有复现这个问题，能说明一下步骤或者录一下操作过程吗？

**Comment by shaokui-gu** [comment]
fix in 0.1.6
